### PR TITLE
Fix memory corruption in shift method

### PR DESCRIPTION
**Pull request by starling13**

### CODE REVIEW

**Comment by Avamander** [comment]
Can't confirm this is a proper fix. Can you explain a bit more what you've fixed?

**Comment by TomasRoj** [comment]
looks like he forgot password to his account xdd

**Comment by abcbarryn** [comment]
Hopefully he can reset his password and explain. I agree it would be good to better understand what the issue is this is supposed to fix before applying this update.

**Comment by TomasRoj** [comment]
Yes tottaly agree but you know. People...

**Comment by starling13** [comment]
Hello, I beg your pardon for such a stupid situation. I forget my PR and don't watch the discussion and it's status for years.
I found some memory corruption while working on my project of Terminal-BASIC arduino-mega based diy computer
https://hackaday.io/project/21588-basic-microcomputer-based-on-arduino.

I'v forked the library on bitbucket https://bitbucket.org/terminalbasicteam/libtvoutex/src/master/
Then I write an SDL2 emulator, which uses TvOut drawing functions but draws the frame buffer on SDL window. I'v found some errors that way and fix them (probably).

**Pull request merged**
